processors:
  active: true

config:
  validation: true

build:
  maxIssues: 0
  excludeCorrectable: false

# Principal Rules
style:
  MagicNumber:
    active: false
  WildcardImport:
    active: true
  UnusedImports:
    active: true
  MaxLineLength:
    active: true
    maxLineLength: 120
  NewLineAtEndOfFile:
    active: false

naming:
  MatchingDeclarationName:
    active: true
  TopLevelPropertyNaming:
    active: false
  PackageNaming:
    active: true

performance:
  SpreadOperator:
    active: true
    excludes:
      - '**/SecureMediaVaultApplication.kt'

potential-bugs:
  ImplicitDefaultLocale:
    active: true
  EqualsWithHashCodeExist:
    active: true

formatting:
  active: true
  android: false
  autoCorrect: true
  FinalNewline:
    active: false
  NoWildcardImports:
    active: false
  Indentation:
    active: true
    indentSize: 4