name: CI to ACR

on:
  push:
    branches: [ main ]
  pull_request:

env:
  IMAGE_NAME: ${{ secrets.ACR_LOGIN_SERVER }}/miapp  # Cambia "miapp" si deseas
  DOCKER_BUILDKIT: 1

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: 'gradle'

      # Detekt (Kotlin + formato)
      - name: Run Detekt
        run: ./gradlew --no-daemon detekt

      - name: Upload Detekt reports
        uses: actions/upload-artifact@v4
        with:
          name: detekt-reports
          path: |
            **/build/reports/detekt/*.html
            **/build/reports/detekt/*.xml
            **/build/reports/detekt/*.sarif

  unit_tests:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: 'gradle'

      - name: Run unit tests
        run: ./gradlew --no-daemon test

  build_jar:
    runs-on: ubuntu-latest
    needs: unit_tests
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: 'gradle'

      # Si es Spring Boot:
      - name: Build JAR (bootJar)
        run: ./gradlew --no-daemon clean bootJar
      # Si NO usas Spring Boot, reemplaza por:
      # run: ./gradlew --no-daemon clean jar

      - name: Upload artifact (JAR)
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: build/libs/*.jar

  docker_build_push:
    runs-on: ubuntu-latest
    needs: build_jar
    steps:
      - uses: actions/checkout@v4

      - name: Download JAR
        uses: actions/download-artifact@v4
        with:
          name: app-jar
          path: build/libs

      - name: Login to ACR
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Compute TAG
        id: tag
        run: echo "TAG=$(date +%Y%m%d-%H%M%S)-${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Detect JAR name
        id: jar
        shell: bash
        run: |
          set -euo pipefail
          shopt -s nullglob
          echo "Contenido de build/libs:"
          ls -lah build/libs

          jars=(build/libs/*.jar)
          if [[ ${#jars[@]} -eq 0 ]]; then
            echo "::error::No se encontró ningún JAR en build/libs"
            exit 1
          fi

          jarname="$(basename "${jars[0]}")"
          echo "JAR_FILE=libs/${jarname}" >> "$GITHUB_OUTPUT"
          echo "Using JAR_FILE=libs/${jarname}"

      - name: Build & Push image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ steps.tag.outputs.TAG }}
            ${{ env.IMAGE_NAME }}:latest
          build-args: |
            JAR_FILE=${{ steps.jar.outputs.JAR_FILE }}
